### ISSUE TITLE
セリフについて

### ISSUE THREAD

**Issue by momdo** [o2project/reset-css-friends#7]
http://friends.o2p.jp/ch01.html#h1-1

>Firefoxではセリフがないフォントで表示されています（図1.1）が、Safariではセリフがあるフォントで表示されます（図1.2）。

説明としては正しいですが、想定読者は「セリフ」という単語を知っている、ということでしょうか。読者は必ずしもフォントに精通しているわけではないと思いますので、個人的には補足説明があってもよいように感じました。

**Comment by kubosho** [comment]
軽く補足を書きます。1文くらい。
